config/routes.rb
Rails.application.routes.draw do

  resources :safe_works do
    put "/approve" => 'safe_works#approvals'
  end
  root to: 'safe_works#index'

  #Login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #Signup
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  #dummy
  resources :dummy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/safe_work.rb
class SafeWork < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "created_by"
    belongs_to :extended_user, class_name: "User", foreign_key: "extended_by"


    attr_reader :extended
    attr_reader :requested_by
    attr_reader :approver

    def requested_by
        if !self.creator
            ""
        else
          self.creator.fullname
        end

    end

    def extended
       if !self.extended_user
        ""
       else
        self.extended_user.fullname
       end
    end

    def approver
        if self.created_by
           return  self.creator.supervisor.fullname
        end
        return nil
    end

    def status
        if self.is_approved
            return "Approved"
        elsif self.is_rejected
            return "Rejected"
        end
    end

    def approved_or_rejected_by
        if self.approved_by
            return User.find(self.approved_by).fullname
        end

    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :safe_works, :foreign_key => "created_by"
    has_many :extended_safe_works, class_name: "SafeWork", foreign_key: "extended_by"
    has_many :approved_safe_works, class_name: "SafeWork", foreign_key: "approved_by"
    has_many :field_engineers, class_name: "User", foreign_key: "manager_id"
    belongs_to :supervisor, class_name: "User", foreign_key: "manager_id", :optional => true
    validates_presence_of :firstname
    validates_presence_of :lastname
    validates_presence_of :email


    def pending_for_approval
        pending_list = []
            self.field_engineers.each do |fe|
                fe.safe_works.each do |sw|
                    if !sw.is_approved && !sw.is_rejected
                        pending_list.push(sw)
                    end
                end
            end
            return pending_list
    end

    def fullname
        "#{self.firstname.capitalize} #{self.lastname.capitalize}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/dummy_controller.rb
class DummyController < ApplicationController
    before_action :authorize

    def index
    end 
end

app/controllers/safe_works_controller.rb
class SafeWorksController < ApplicationController
  before_action :set_safe_work, only: [:show, :approvals,:edit, :update, :destroy]
  before_action :authorize
  before_action :set_current_user
  # GET /safe_works
  # GET /safe_works.json
  def index
    @safe_works = @user.safe_works
    @pending_for_approval = @user.pending_for_approval
  end

  # GET /safe_works/1
  # GET /safe_works/1.json
  def show
  end

  # GET /safe_works/new
  def new
    @safe_work = SafeWork.new
  end

  # GET /safe_works/1/edit
  def edit
  end

  # POST /safe_works
  # POST /safe_works.json
  def create
    @safe_work = SafeWork.new(safe_work_params)

    respond_to do |format|
      if @safe_work.save
        format.html { redirect_to @safe_work, notice: 'Safe work was successfully created.' }
        format.json { render :show, status: :created, location: @safe_work }
      else
        format.html { render :new }
        format.json { render json: @safe_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /safe_works/1
  # PATCH/PUT /safe_works/1.json
  def update
    if @safe_work.is_rejected == true
      @safe_work.is_rejected = nil
    end
    respond_to do |format|
      if @safe_work.update(safe_work_params)
        format.html { redirect_to @safe_work, notice: 'Safe work was successfully updated.' }
        format.json { render :show, status: :ok, location: @safe_work }
      else
        format.html { render :edit }
        format.json { render json: @safe_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /safe_works/1
  # DELETE /safe_works/1.json
  def destroy
    @safe_work.destroy
    respond_to do |format|
      format.html { redirect_to safe_works_url, notice: 'Safe work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approvals
    if params[:commit] == "Approve"
      @safe_work.is_approved = true
    elsif params[:commit] == "Reject"
      @safe_work.is_rejected = true
    end
    @safe_work.approved_by = @user.id
    @safe_work.comments = params[:safe_work_approve][:comments]
      respond_to do |format|
      if @safe_work.save!
        format.html {redirect_to safe_works_url, notice: "Request approved"}
        format.json {head :no_content}
      end
    end

  end

  private

    def set_current_user
      @user = current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_safe_work
      id = params[:id] || params[:safe_work_id]
      @safe_work = SafeWork.find(id)
    end

    # Only allow a list of trusted parameters through.
    def safe_work_params
      params.fetch(:safe_work, {}).permit(:company_name,:comments, :crew_size, :is_snv_lavalin,:is_sub_contractor,:issued_datetime, :extended_datetime,:extended_by,:emergency_meeting_point,:location,:description_of_work, :created_by )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:email]) || User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to safe_works_path
    else 
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email,:username, :string, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_helper.rb
module DummyHelper
end

app/helpers/safe_works_helper.rb
module SafeWorksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= stylesheet_link_tag "styles.css" %>
    <%= stylesheet_link_tag "mdb.min.css" %>
    <%= stylesheet_link_tag "style.css" %>
    <title>new</title>
    <style>
            body {
              background: linear-gradient(to bottom, rgb(0, 0, 0), rgba(219, 165, 17, 0.233)), url(<%= asset_path 'Is-It-Safe-to-Buy-Used-Safety-Equipment.jpg'%> );
              background-repeat: no-repeat;
              background-attachment: fixed;
              background-size: 100% 100%;
            }
    </style>
  </head>
  <body>

      <nav class="navbar navbar-dark bg-dark" style="background: #00000069 !important;">
        <%= link_to "Safework" , root_path, {class:"navbar-brand mb-0 h1"}%>

        </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  </body>

app/views/safe_works/_approval_form.html.erb
<style>
    textarea{
        background: transparent !important;
        color: white !important;
    }
</style>
    <%= f.text_area :comments, class:"form-control", required: true%>
    <%= f.submit "Approve", disable_with: 'Approveing...', class: "btn btn-sm btn-warning"%>
    <%= f.submit "Reject", disable_with: 'Rejecting...'%>

app/views/safe_works/_form.html.erb
<style>
  .bg-warning, .btn-warning{
    background-color: #da960f !important;
  }
</style>

<h2 class="h2 text-warning text-center">Safe Work Permit Form</h2>

<%= form_with(model: safe_work, local: true) do |form| %>
  <% if safe_work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(safe_work.errors.count, "error") %> prohibited this safe_work from being saved:</h2>

      <ul>
        <% safe_work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-12 pad ">
          <label for="confinedspace"> CONFINED SPACE</label>
          <input type="checkbox" id="confinedspace" >
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pad">
        <label for="hotwork"> HOT WORK</label>
        <input type="checkbox" id="hotwork" >
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pad">
        <label for="excavation"> EXCAVATION</label>
        <input type="checkbox" id="excavation" >
      </div>
      <div class="col-lg-3 col-md-6 col-sm-12 pad ">
        <label for="de_energization">DE-ENERGIZATION (LOTO)</label>
        <input type="checkbox" id="de_energization">
      </div>
  </div>

  <div class=" row bg-warning text-white font-weight-bold ">PART I:WORK DETAILS</div>

    <div class="row pt-4">
          <div class="col-md-4 col-sm-12 form-group">
            <%= form.label :is_snv_lavalin, class: "form-lable-col" %>
            <%= form.check_box :is_snv_lavalin , class: "col-4" %>
          </div>
          <div class="col-md-4 col-sm-12 form-group">
            <%= form.label :is_sub_contractor, class: "form-lable-col" %>
            <%= form.check_box :is_sub_contractor, class: "col-4" %>
          </div>
          <div class="col-md-4 col-sm-12 form-group">
            <div class="row">
              <%= form.label :crew_size, class: "form-lable-col col-4" %>
              <%= form.number_field :crew_size, class: "form-control col-5" %>
            </div>
          </div>
    </div>
    <div class="row pt-4">
      <div class="col-4 ">
        <div class="row form-group">
          <%= form.label :issued_datetime, class: "form-lable-col col-4" %>
          <%= form.datetime_field :issued_datetime, class: "form-control col-5" %>
        </div>
      </div>
      <div class="col-4">
        <div class="row form-group">
          <label for="date_expired" class="form-lable-col col-4">Date expired</label>
          <input  type="datetime-local" id="expired" name="expired" class="form-control col-5">
        </div>
      </div>
      <div class="col-4">
          <div class="row form-group">
            <%= form.label :extended_datetime, class: "form-lable-col col-4" %>
            <%= form.datetime_field :extended_datetime, class: "form-control col-5" %>
          </div>
      </div>
    </div>
    <div class="row pt-4">
        <div class="col-4">
          <div class="row form-group">
            <%= form.label :extended_by, class: "form-lable-col col-4" %>
            <%= form.select(:extended_by, User.all.map {|d| ["#{d.firstname} #{d.lastname}", d.id]}, {:include_blank => "Select"}, {:class => "form-control col-5"} )%>
          </div>
        </div>
        <div class="col-4">
          <div class="row form-group">
            <%= form.label :emergency_meeting_point, class: "form-lable-col col-4" %>
            <%= form.text_field :emergency_meeting_point, class: "form-control col-5" %>
          </div>
        </div>
        <div class="col-4">
          <div class="row form-group">
            <%= form.label :location, class: "form-lable-col col-4" %>
            <%= form.text_field :location, class: "form-control col-5" %>
          </div>
        </div>
    </div>
    <div class="row pt-4">
      <div class="col-8 ">
          <div class="row">
              <%= form.label :description_of_work, "Description",class: "form-lable-col col-2" %>
              <%= form.text_area :description_of_work, class: "form-control col-3" %>
          </div>
      </div>
    </div>

  <%= form.hidden_field :created_by, value: "#{current_user().id}"%>
  <div class="row">
     <div class=" mx-auto">
      <%=form.submit nil, class: "btn btn-sm btn-warning"%>
     </div>
  </div>
<% end %>

app/views/safe_works/edit.html.erb
<h1>Editing Safe Work</h1>

<%= render 'form', safe_work: @safe_work %>

<%= link_to 'Show', @safe_work %> |
<%= link_to 'Back', safe_works_path %>

app/views/safe_works/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="background: #0000005c;">
<div class="card-body">
<div class="table-responsive">
<caption>My Requests (<%="#{@safe_works.count}"%>)</caption>
<table class="table table-sm table-bordered">
  <thead style="color: white;">
    <tr>
    <th>Company Name</th>
    <th>Crew Size</th>
    <th>SNV Lavalin</th>
    <th>Sub Contractor</th>
    <th>Issued Date & Time</th>
    <th>Extended  Date & Time</th>
    <th>Extended By</th>
    <th>Created Date & Time</th>
    <th>Created By</th>
    <th>Approver</th>
    <th>Status</th>
    <th>Approved/Rejected By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody style="color:white;">
    <% @safe_works.each do |safe_work| %>
      <tr>
      <td><%= safe_work.company_name%></td>
      <td><%= safe_work.crew_size%></td>
      <td><%= safe_work.is_snv_lavalin%></td>
      <td><%= safe_work.is_sub_contractor%></td>
      <td><%= safe_work.issued_datetime%></td>
      <td><%= safe_work.extended_datetime%></td>
      <td><%= safe_work.extended%></td>
      <td><%= safe_work.created_at%></td>
      <td><%= safe_work.requested_by%></td>
      <td><%= safe_work.approver%></td>
      <td><%= safe_work.status%></td>
      <td><%= safe_work.approved_or_rejected_by%></td>
        <td><%= link_to 'Show', safe_work %></td>
        <%if !safe_work.is_approved%>
        <td><%= link_to 'Edit', edit_safe_work_path(safe_work)%></td>
        <%else%>
        <td></td>
        <%end%>
        <%if !safe_work.comments%>
        <td><%= link_to 'Destroy', safe_work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>
<% if !@pending_for_approval.empty? %>
<div class="card" style="background:#0000005c;">
<div class="card-body">
<div class="table-responsive">
  <caption>Pending for My Approval(<%= @pending_for_approval.count%>)</caption>
  <table class="table table-sm table-bordered">
    <thead style="color: white">
      <tr>
      <th>Company Name</th>
      <th>Crew Size</th>
      <th>SNV Lavalin</th>
      <th>Sub Contractor</th>
      <th>Issued Date & Time</th>
      <th>Extended  Date & Time</th>
      <th>Extended By</th>
      <th>Created Date & Time</th>
      <th>Created By</th>
      <th></th>
      </tr>
  </thead>
  <tbody style="color: white">
  <% @pending_for_approval.each do |pending| %>
    <tr>
    <td><%= pending.company_name%></td>
    <td><%= pending.crew_size%></td>
    <td><%= pending.is_snv_lavalin%></td>
    <td><%= pending.is_sub_contractor%></td>
    <td><%= pending.issued_datetime%></td>
    <td><%= pending.extended_datetime%></td>
    <td><%= pending.extended%></td>
    <td><%= pending.created_at%></td>
    <td><%= pending.requested_by%></td>
      <td><%= link_to 'View', safe_work_path(pending), {class: "text-white"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<%end%>
</div>
</div>


<%= link_to 'New Safe Work', new_safe_work_path %>

app/views/safe_works/new.html.erb
<style>
    input, textarea, select, label {
        background: transparent !important;
        color: white !important;
    }
</style>
<div class="row pt-4">
    <div class="card col-10 mx-auto" style="background: #0000005c;">
        <div class="card-body">
            <%= render 'form', safe_work: @safe_work %>
        </div>
    </div>
</div>
<%= link_to 'Back', safe_works_path %>

app/views/safe_works/show.html.erb
<p id="notice"><%= notice %></p>
<% SafeWork.column_names.each do |column|%>

    <div class="row">
        <div class="col-3">
           <p><%= column.humanize%></p>
        </div>
        <div class="col-4">
            <p><%= @safe_work[column]%></p>
        </div>
    </div>


<%end%>

<% if @user.pending_for_approval.include?(@safe_work)%>

<%= form_with scope: :safe_work_approve, url: safe_work_approve_path(@safe_work), method: :put do |form| %>
    <%= render :partial => "approval_form", :locals => {:f => form}%>
<% end %>
<%else%>
<%if !@safe_work.is_approved%>
<%= link_to 'Edit', edit_safe_work_path(@safe_work) %>
|<%end%>
<%= link_to 'Back', safe_works_path %>
<%end%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :firstname, class: "form-lable-col col-4" %>
    <div class="col-8">
      <%= form.text_field :firstname, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :lastname, class: "form-label-col col-4" %>
    <div class="col-8">
      <%= form.text_field :lastname, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :email, class: "form-label-col col-4" %>
    <div class="col-8">
      <%= form.text_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :username, class: "form-label-col col-4" %>
    <div class="col-8">
      <%= form.text_field :username, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password, class:"form-label-col col-4" %>
    <div class="col-8">
      <%= form.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password_confirmation, class: "form-label-col col-4" %>
    <div class="col-8">
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
</div>

  <div class="row">
    <div class="col-2 mx-auto">
    <%= form.submit nil, class: "btn btn-sm btn-outline-primary mx-auto" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>String</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.string %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
<div class="col-4 mx-auto p-4 border rounded shadow-lg mb-5 mt-5 bg-white">
<%= render 'form', user: @user %>
<div class="col-2">
<%= link_to 'Back', users_path %>
</div>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>String:</strong>
  <%= @user.string %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>